---
title: "Frequency Estimates - Search Engine"
date: "Last updated `r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    code_folding: hide
---

<u>Please consult the reference listed below for more information about this project.</u><br>
[--- citation blinded for review ---]
<!-- 
<font size="2">Condon, D. M., & McDougald, S. (under review). Frequency of use metrics for American English personality descriptors: Extensions of Roivainen's internet search methodology. *Journal TBD*.</font>
-->

```{r, include = F}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

```{r}
library(here) # for engaging with working environment
library(Hmisc) # for weighted means
library(DT) # for viewing data tables
library(tidyverse) # for data cleaning and manipulation
library(dataverse)
library(data.table)
```

```{r}
# create table 
serps = read.csv(here("data/serps/serps_freq_index.csv"))
serps$person_zscore <- round(serps$person_zscore, 4)
serps$woman_zscore <- round(serps$woman_zscore, 4)
serps$man_zscore <- round(serps$man_zscore, 4)
serps$girl_zscore <- round(serps$boy_zscore, 4)
serps$boy_zscore <- round(serps$boy_zscore, 4)

# fix characters
#serps$TDA <- sub("blas\x8e", "blasé", serps$TDA)
#serps$TDA <- sub("FALSE", "false", serps$TDA)

serps_prop = serps %>%
  DT::datatable( # put into interactive HTML table
    colnames = c("Adjective", "+person", "+woman", "+man", "+girl", "+boy", "index"), #colnames
    options = list(
      lengthMenu = list(c(10, 50, -1), c('10', '50', 'All')),
        pageLength = 10
    ),
    filter = "top", # can filter
    rownames = F # don't need rownames
  )
```



